[Logger]
level = "INFO"
path ="./calendar.logger"

[HTTPserver]
host = "localhost"
port = "8080"

[GRPCserver]
host = "localhost"
port = "50051"

[Storage]
type = "memory"

[Database]
user = "test"
password = "test"
host = "localhost"
port = 5432
nameDb = "calendar.db"

